/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/_manager'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/_driver'
import { Route as AuthenticatedManagerManagerIndexRouteImport } from './routes/_authenticated/_manager/manager/index'
import { Route as AuthDriverInviteTokenRouteImport } from './routes/auth/driver/invite/$token'
import { Route as AuthenticatedDriverDriverActiveAssignmentsRouteImport } from './routes/_authenticated/_driver/driver/active-assignments'
import { Route as AuthenticatedManagerManagerWarehouseIndexRouteImport } from './routes/_authenticated/_manager/manager/warehouse/index'
import { Route as AuthenticatedManagerManagerTrucksIndexRouteImport } from './routes/_authenticated/_manager/manager/trucks/index'
import { Route as AuthenticatedManagerManagerShipmentsIndexRouteImport } from './routes/_authenticated/_manager/manager/shipments/index'
import { Route as AuthenticatedManagerManagerDriversIndexRouteImport } from './routes/_authenticated/_manager/manager/drivers/index'
import { Route as AuthenticatedManagerManagerDeliveryJobsIndexRouteImport } from './routes/_authenticated/_manager/manager/delivery-jobs/index'
import { Route as AuthenticatedManagerManagerShipmentsCreateRouteImport } from './routes/_authenticated/_manager/manager/shipments/create'
import { Route as AuthenticatedManagerManagerShipmentsIdRouteImport } from './routes/_authenticated/_manager/manager/shipments/$id'
import { Route as AuthenticatedManagerManagerDeliveryJobsCreateRouteImport } from './routes/_authenticated/_manager/manager/delivery-jobs/create'
import { Route as AuthenticatedManagerManagerDeliveryJobsIdRouteImport } from './routes/_authenticated/_manager/manager/delivery-jobs/$id'
import { Route as AuthenticatedManagerManagerDeliveryJobsResultIdRouteImport } from './routes/_authenticated/_manager/manager/delivery-jobs-result/$id'
import { Route as AuthenticatedDriverDriverAssignmentsIdRouteImport } from './routes/_authenticated/_driver/driver/assignments/$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/_manager',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/_driver',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerManagerIndexRoute =
  AuthenticatedManagerManagerIndexRouteImport.update({
    id: '/manager/',
    path: '/manager/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthDriverInviteTokenRoute = AuthDriverInviteTokenRouteImport.update({
  id: '/auth/driver/invite/$token',
  path: '/auth/driver/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDriverDriverActiveAssignmentsRoute =
  AuthenticatedDriverDriverActiveAssignmentsRouteImport.update({
    id: '/driver/active-assignments',
    path: '/driver/active-assignments',
    getParentRoute: () => AuthenticatedDriverRoute,
  } as any)
const AuthenticatedManagerManagerWarehouseIndexRoute =
  AuthenticatedManagerManagerWarehouseIndexRouteImport.update({
    id: '/manager/warehouse/',
    path: '/manager/warehouse/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerManagerTrucksIndexRoute =
  AuthenticatedManagerManagerTrucksIndexRouteImport.update({
    id: '/manager/trucks/',
    path: '/manager/trucks/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerManagerShipmentsIndexRoute =
  AuthenticatedManagerManagerShipmentsIndexRouteImport.update({
    id: '/manager/shipments/',
    path: '/manager/shipments/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerManagerDriversIndexRoute =
  AuthenticatedManagerManagerDriversIndexRouteImport.update({
    id: '/manager/drivers/',
    path: '/manager/drivers/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerManagerDeliveryJobsIndexRoute =
  AuthenticatedManagerManagerDeliveryJobsIndexRouteImport.update({
    id: '/manager/delivery-jobs/',
    path: '/manager/delivery-jobs/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerManagerShipmentsCreateRoute =
  AuthenticatedManagerManagerShipmentsCreateRouteImport.update({
    id: '/manager/shipments/create',
    path: '/manager/shipments/create',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerManagerShipmentsIdRoute =
  AuthenticatedManagerManagerShipmentsIdRouteImport.update({
    id: '/manager/shipments/$id',
    path: '/manager/shipments/$id',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerManagerDeliveryJobsCreateRoute =
  AuthenticatedManagerManagerDeliveryJobsCreateRouteImport.update({
    id: '/manager/delivery-jobs/create',
    path: '/manager/delivery-jobs/create',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerManagerDeliveryJobsIdRoute =
  AuthenticatedManagerManagerDeliveryJobsIdRouteImport.update({
    id: '/manager/delivery-jobs/$id',
    path: '/manager/delivery-jobs/$id',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerManagerDeliveryJobsResultIdRoute =
  AuthenticatedManagerManagerDeliveryJobsResultIdRouteImport.update({
    id: '/manager/delivery-jobs-result/$id',
    path: '/manager/delivery-jobs-result/$id',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedDriverDriverAssignmentsIdRoute =
  AuthenticatedDriverDriverAssignmentsIdRouteImport.update({
    id: '/driver/assignments/$id',
    path: '/driver/assignments/$id',
    getParentRoute: () => AuthenticatedDriverRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/driver/active-assignments': typeof AuthenticatedDriverDriverActiveAssignmentsRoute
  '/auth/driver/invite/$token': typeof AuthDriverInviteTokenRoute
  '/manager': typeof AuthenticatedManagerManagerIndexRoute
  '/driver/assignments/$id': typeof AuthenticatedDriverDriverAssignmentsIdRoute
  '/manager/delivery-jobs-result/$id': typeof AuthenticatedManagerManagerDeliveryJobsResultIdRoute
  '/manager/delivery-jobs/$id': typeof AuthenticatedManagerManagerDeliveryJobsIdRoute
  '/manager/delivery-jobs/create': typeof AuthenticatedManagerManagerDeliveryJobsCreateRoute
  '/manager/shipments/$id': typeof AuthenticatedManagerManagerShipmentsIdRoute
  '/manager/shipments/create': typeof AuthenticatedManagerManagerShipmentsCreateRoute
  '/manager/delivery-jobs': typeof AuthenticatedManagerManagerDeliveryJobsIndexRoute
  '/manager/drivers': typeof AuthenticatedManagerManagerDriversIndexRoute
  '/manager/shipments': typeof AuthenticatedManagerManagerShipmentsIndexRoute
  '/manager/trucks': typeof AuthenticatedManagerManagerTrucksIndexRoute
  '/manager/warehouse': typeof AuthenticatedManagerManagerWarehouseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/driver/active-assignments': typeof AuthenticatedDriverDriverActiveAssignmentsRoute
  '/auth/driver/invite/$token': typeof AuthDriverInviteTokenRoute
  '/manager': typeof AuthenticatedManagerManagerIndexRoute
  '/driver/assignments/$id': typeof AuthenticatedDriverDriverAssignmentsIdRoute
  '/manager/delivery-jobs-result/$id': typeof AuthenticatedManagerManagerDeliveryJobsResultIdRoute
  '/manager/delivery-jobs/$id': typeof AuthenticatedManagerManagerDeliveryJobsIdRoute
  '/manager/delivery-jobs/create': typeof AuthenticatedManagerManagerDeliveryJobsCreateRoute
  '/manager/shipments/$id': typeof AuthenticatedManagerManagerShipmentsIdRoute
  '/manager/shipments/create': typeof AuthenticatedManagerManagerShipmentsCreateRoute
  '/manager/delivery-jobs': typeof AuthenticatedManagerManagerDeliveryJobsIndexRoute
  '/manager/drivers': typeof AuthenticatedManagerManagerDriversIndexRoute
  '/manager/shipments': typeof AuthenticatedManagerManagerShipmentsIndexRoute
  '/manager/trucks': typeof AuthenticatedManagerManagerTrucksIndexRoute
  '/manager/warehouse': typeof AuthenticatedManagerManagerWarehouseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/_driver': typeof AuthenticatedDriverRouteWithChildren
  '/_authenticated/_manager': typeof AuthenticatedManagerRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/_driver/driver/active-assignments': typeof AuthenticatedDriverDriverActiveAssignmentsRoute
  '/auth/driver/invite/$token': typeof AuthDriverInviteTokenRoute
  '/_authenticated/_manager/manager/': typeof AuthenticatedManagerManagerIndexRoute
  '/_authenticated/_driver/driver/assignments/$id': typeof AuthenticatedDriverDriverAssignmentsIdRoute
  '/_authenticated/_manager/manager/delivery-jobs-result/$id': typeof AuthenticatedManagerManagerDeliveryJobsResultIdRoute
  '/_authenticated/_manager/manager/delivery-jobs/$id': typeof AuthenticatedManagerManagerDeliveryJobsIdRoute
  '/_authenticated/_manager/manager/delivery-jobs/create': typeof AuthenticatedManagerManagerDeliveryJobsCreateRoute
  '/_authenticated/_manager/manager/shipments/$id': typeof AuthenticatedManagerManagerShipmentsIdRoute
  '/_authenticated/_manager/manager/shipments/create': typeof AuthenticatedManagerManagerShipmentsCreateRoute
  '/_authenticated/_manager/manager/delivery-jobs/': typeof AuthenticatedManagerManagerDeliveryJobsIndexRoute
  '/_authenticated/_manager/manager/drivers/': typeof AuthenticatedManagerManagerDriversIndexRoute
  '/_authenticated/_manager/manager/shipments/': typeof AuthenticatedManagerManagerShipmentsIndexRoute
  '/_authenticated/_manager/manager/trucks/': typeof AuthenticatedManagerManagerTrucksIndexRoute
  '/_authenticated/_manager/manager/warehouse/': typeof AuthenticatedManagerManagerWarehouseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/auth/login'
    | '/auth/signup'
    | '/driver/active-assignments'
    | '/auth/driver/invite/$token'
    | '/manager'
    | '/driver/assignments/$id'
    | '/manager/delivery-jobs-result/$id'
    | '/manager/delivery-jobs/$id'
    | '/manager/delivery-jobs/create'
    | '/manager/shipments/$id'
    | '/manager/shipments/create'
    | '/manager/delivery-jobs'
    | '/manager/drivers'
    | '/manager/shipments'
    | '/manager/trucks'
    | '/manager/warehouse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/auth/login'
    | '/auth/signup'
    | '/driver/active-assignments'
    | '/auth/driver/invite/$token'
    | '/manager'
    | '/driver/assignments/$id'
    | '/manager/delivery-jobs-result/$id'
    | '/manager/delivery-jobs/$id'
    | '/manager/delivery-jobs/create'
    | '/manager/shipments/$id'
    | '/manager/shipments/create'
    | '/manager/delivery-jobs'
    | '/manager/drivers'
    | '/manager/shipments'
    | '/manager/trucks'
    | '/manager/warehouse'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/unauthorized'
    | '/_authenticated/_driver'
    | '/_authenticated/_manager'
    | '/auth/login'
    | '/auth/signup'
    | '/_authenticated/_driver/driver/active-assignments'
    | '/auth/driver/invite/$token'
    | '/_authenticated/_manager/manager/'
    | '/_authenticated/_driver/driver/assignments/$id'
    | '/_authenticated/_manager/manager/delivery-jobs-result/$id'
    | '/_authenticated/_manager/manager/delivery-jobs/$id'
    | '/_authenticated/_manager/manager/delivery-jobs/create'
    | '/_authenticated/_manager/manager/shipments/$id'
    | '/_authenticated/_manager/manager/shipments/create'
    | '/_authenticated/_manager/manager/delivery-jobs/'
    | '/_authenticated/_manager/manager/drivers/'
    | '/_authenticated/_manager/manager/shipments/'
    | '/_authenticated/_manager/manager/trucks/'
    | '/_authenticated/_manager/manager/warehouse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthDriverInviteTokenRoute: typeof AuthDriverInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_manager': {
      id: '/_authenticated/_manager'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_driver': {
      id: '/_authenticated/_driver'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_manager/manager/': {
      id: '/_authenticated/_manager/manager/'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerManagerIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/auth/driver/invite/$token': {
      id: '/auth/driver/invite/$token'
      path: '/auth/driver/invite/$token'
      fullPath: '/auth/driver/invite/$token'
      preLoaderRoute: typeof AuthDriverInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_driver/driver/active-assignments': {
      id: '/_authenticated/_driver/driver/active-assignments'
      path: '/driver/active-assignments'
      fullPath: '/driver/active-assignments'
      preLoaderRoute: typeof AuthenticatedDriverDriverActiveAssignmentsRouteImport
      parentRoute: typeof AuthenticatedDriverRoute
    }
    '/_authenticated/_manager/manager/warehouse/': {
      id: '/_authenticated/_manager/manager/warehouse/'
      path: '/manager/warehouse'
      fullPath: '/manager/warehouse'
      preLoaderRoute: typeof AuthenticatedManagerManagerWarehouseIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/_manager/manager/trucks/': {
      id: '/_authenticated/_manager/manager/trucks/'
      path: '/manager/trucks'
      fullPath: '/manager/trucks'
      preLoaderRoute: typeof AuthenticatedManagerManagerTrucksIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/_manager/manager/shipments/': {
      id: '/_authenticated/_manager/manager/shipments/'
      path: '/manager/shipments'
      fullPath: '/manager/shipments'
      preLoaderRoute: typeof AuthenticatedManagerManagerShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/_manager/manager/drivers/': {
      id: '/_authenticated/_manager/manager/drivers/'
      path: '/manager/drivers'
      fullPath: '/manager/drivers'
      preLoaderRoute: typeof AuthenticatedManagerManagerDriversIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/_manager/manager/delivery-jobs/': {
      id: '/_authenticated/_manager/manager/delivery-jobs/'
      path: '/manager/delivery-jobs'
      fullPath: '/manager/delivery-jobs'
      preLoaderRoute: typeof AuthenticatedManagerManagerDeliveryJobsIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/_manager/manager/shipments/create': {
      id: '/_authenticated/_manager/manager/shipments/create'
      path: '/manager/shipments/create'
      fullPath: '/manager/shipments/create'
      preLoaderRoute: typeof AuthenticatedManagerManagerShipmentsCreateRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/_manager/manager/shipments/$id': {
      id: '/_authenticated/_manager/manager/shipments/$id'
      path: '/manager/shipments/$id'
      fullPath: '/manager/shipments/$id'
      preLoaderRoute: typeof AuthenticatedManagerManagerShipmentsIdRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/_manager/manager/delivery-jobs/create': {
      id: '/_authenticated/_manager/manager/delivery-jobs/create'
      path: '/manager/delivery-jobs/create'
      fullPath: '/manager/delivery-jobs/create'
      preLoaderRoute: typeof AuthenticatedManagerManagerDeliveryJobsCreateRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/_manager/manager/delivery-jobs/$id': {
      id: '/_authenticated/_manager/manager/delivery-jobs/$id'
      path: '/manager/delivery-jobs/$id'
      fullPath: '/manager/delivery-jobs/$id'
      preLoaderRoute: typeof AuthenticatedManagerManagerDeliveryJobsIdRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/_manager/manager/delivery-jobs-result/$id': {
      id: '/_authenticated/_manager/manager/delivery-jobs-result/$id'
      path: '/manager/delivery-jobs-result/$id'
      fullPath: '/manager/delivery-jobs-result/$id'
      preLoaderRoute: typeof AuthenticatedManagerManagerDeliveryJobsResultIdRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/_driver/driver/assignments/$id': {
      id: '/_authenticated/_driver/driver/assignments/$id'
      path: '/driver/assignments/$id'
      fullPath: '/driver/assignments/$id'
      preLoaderRoute: typeof AuthenticatedDriverDriverAssignmentsIdRouteImport
      parentRoute: typeof AuthenticatedDriverRoute
    }
  }
}

interface AuthenticatedDriverRouteChildren {
  AuthenticatedDriverDriverActiveAssignmentsRoute: typeof AuthenticatedDriverDriverActiveAssignmentsRoute
  AuthenticatedDriverDriverAssignmentsIdRoute: typeof AuthenticatedDriverDriverAssignmentsIdRoute
}

const AuthenticatedDriverRouteChildren: AuthenticatedDriverRouteChildren = {
  AuthenticatedDriverDriverActiveAssignmentsRoute:
    AuthenticatedDriverDriverActiveAssignmentsRoute,
  AuthenticatedDriverDriverAssignmentsIdRoute:
    AuthenticatedDriverDriverAssignmentsIdRoute,
}

const AuthenticatedDriverRouteWithChildren =
  AuthenticatedDriverRoute._addFileChildren(AuthenticatedDriverRouteChildren)

interface AuthenticatedManagerRouteChildren {
  AuthenticatedManagerManagerIndexRoute: typeof AuthenticatedManagerManagerIndexRoute
  AuthenticatedManagerManagerDeliveryJobsResultIdRoute: typeof AuthenticatedManagerManagerDeliveryJobsResultIdRoute
  AuthenticatedManagerManagerDeliveryJobsIdRoute: typeof AuthenticatedManagerManagerDeliveryJobsIdRoute
  AuthenticatedManagerManagerDeliveryJobsCreateRoute: typeof AuthenticatedManagerManagerDeliveryJobsCreateRoute
  AuthenticatedManagerManagerShipmentsIdRoute: typeof AuthenticatedManagerManagerShipmentsIdRoute
  AuthenticatedManagerManagerShipmentsCreateRoute: typeof AuthenticatedManagerManagerShipmentsCreateRoute
  AuthenticatedManagerManagerDeliveryJobsIndexRoute: typeof AuthenticatedManagerManagerDeliveryJobsIndexRoute
  AuthenticatedManagerManagerDriversIndexRoute: typeof AuthenticatedManagerManagerDriversIndexRoute
  AuthenticatedManagerManagerShipmentsIndexRoute: typeof AuthenticatedManagerManagerShipmentsIndexRoute
  AuthenticatedManagerManagerTrucksIndexRoute: typeof AuthenticatedManagerManagerTrucksIndexRoute
  AuthenticatedManagerManagerWarehouseIndexRoute: typeof AuthenticatedManagerManagerWarehouseIndexRoute
}

const AuthenticatedManagerRouteChildren: AuthenticatedManagerRouteChildren = {
  AuthenticatedManagerManagerIndexRoute: AuthenticatedManagerManagerIndexRoute,
  AuthenticatedManagerManagerDeliveryJobsResultIdRoute:
    AuthenticatedManagerManagerDeliveryJobsResultIdRoute,
  AuthenticatedManagerManagerDeliveryJobsIdRoute:
    AuthenticatedManagerManagerDeliveryJobsIdRoute,
  AuthenticatedManagerManagerDeliveryJobsCreateRoute:
    AuthenticatedManagerManagerDeliveryJobsCreateRoute,
  AuthenticatedManagerManagerShipmentsIdRoute:
    AuthenticatedManagerManagerShipmentsIdRoute,
  AuthenticatedManagerManagerShipmentsCreateRoute:
    AuthenticatedManagerManagerShipmentsCreateRoute,
  AuthenticatedManagerManagerDeliveryJobsIndexRoute:
    AuthenticatedManagerManagerDeliveryJobsIndexRoute,
  AuthenticatedManagerManagerDriversIndexRoute:
    AuthenticatedManagerManagerDriversIndexRoute,
  AuthenticatedManagerManagerShipmentsIndexRoute:
    AuthenticatedManagerManagerShipmentsIndexRoute,
  AuthenticatedManagerManagerTrucksIndexRoute:
    AuthenticatedManagerManagerTrucksIndexRoute,
  AuthenticatedManagerManagerWarehouseIndexRoute:
    AuthenticatedManagerManagerWarehouseIndexRoute,
}

const AuthenticatedManagerRouteWithChildren =
  AuthenticatedManagerRoute._addFileChildren(AuthenticatedManagerRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRouteWithChildren
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDriverRoute: AuthenticatedDriverRouteWithChildren,
  AuthenticatedManagerRoute: AuthenticatedManagerRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthDriverInviteTokenRoute: AuthDriverInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
